name: Build Blender for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set Up Android NDK
        uses: android/ndk-build-action@v1
        with:
          ndk-version: r25c

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build python3 python3-pip cmake
          pip3 install --upgrade pip
          pip3 install mako

      - name: Configure CMake for Android
        run: |
          mkdir -p build-android
          cd build-android
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID=ON \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DANDROID_NDK=$ANDROID_NDK_ROOT \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -GNinja

      - name: Build Blender
        run: |
          cd build-android
          ninja

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: blender-android
          path: build-android/bin/
