name: Build Blender for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d $HOME
          echo "ANDROID_NDK=$HOME/android-ndk-r25c" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build python3 python3-pip cmake build-essential libjpeg-dev libpng-dev libz-dev libopenexr-dev
          pip3 install --upgrade pip
          pip3 install mako

      - name: Verify JPEG Installation
        run: |
          if ! dpkg -s libjpeg-dev > /dev/null 2>&1; then
            echo "libjpeg-dev is not installed. Exiting."
            exit 1
          fi

      - name: Clean and Configure CMake for Android
        run: |
          rm -rf build-android
          mkdir build-android
          cd build-android
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID=ON \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DANDROID_NDK=$HOME/android-ndk-r25c \
            -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk-r25c/build/cmake/android.toolchain.cmake \
            -GNinja

      - name: Build Blender
        run: |
          cd build-android
          ninja

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: blender-android
          path: build-android/
